### ISSUE TITLE
Bug: l10n.message() could not interpolate variable “line”

### ISSUE THREAD

**Issue by r12a** [w3c/specberus#437] opened 2016-06-22 10:39 UTC
no idea what that means

Found while checking https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/predefined-counter-styles/?specStatus=WD;shortName=predefined-counter-styles

**Comment by tripu** [comment] 2016-06-24 10:27
Duplicate of #376.

**Closed by tripu** 2016-06-24 10:27 UTC
Labels: from-template
