### ISSUE TITLE
Bug: unclear report...

### ISSUE THREAD

**Issue by iherman** [w3c/specberus#424] opened 2016-06-14 11:22 UTC
By running the check below, I get 8 almost identical bugs; see the screen dump below. I would *think* these are the bugs of the system; if not, and they refer to bugs in the file, they are fairly ununderstandable...

Ivan

Found [while checking `http://w3c.github.io/web-annotation/admin/TR/annotation-protocol/Overview.html`](https://www.w3.org/pubrules/?url=http%3A%2F%2Fw3c.github.io%2Fweb-annotation%2Fadmin%2FTR%2Fannotation-protocol%2FOverview.html&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

![screen shot 2016-06-14 at 13 21 08](https://cloud.githubusercontent.com/assets/520723/16040953/22ad926e-3233-11e6-802c-c6989ff56d6f.png)

**Comment by deniak** [comment] 2016-06-14 13:41
A small bug on the rule selectors was introduced in the last release. This is now fixed.

**Closed by deniak** 2016-06-14 13:41 UTC
Labels: from-template

**Comment by tripu** [comment] 2016-07-11 09:51
@deniak, I think this is #386, and I haven't submitted a PR for that one yet&hellip;

**Comment by deniak** [comment] 2016-07-11 15:31
That's the same error but the cause is different. The error no longer appears if you check the document above.
