### ISSUE TITLE
h2-toc missing rule

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#359] opened 2016-05-16 16:36 UTC
This one is puzzling me.

https://labs.w3.org/pubrules/?url=https%3A%2F%2Frawgit.com%2Fw3c%2Fttml2%2Fttml2-WD-201605XX%2Fspec%2Fttml2.html&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2015

keeps complaining about the h2 in the <nav toc> missing:
[[
ERROR: There is no table of contents inside a navigation element (<nav id="toc"> … <h2>Table of Contents</h2> … </nav>).
]]

But it's there:
https://rawgit.com/w3c/ttml2/ttml2-WD-201605XX/spec/ttml2.html

Running the up-to-date master branch of specberus locally doesn't return that error on the *same online document*.

http://localhost:3001/?url=https%3A%2F%2Frawgit.com%2Fw3c%2Fttml2%2Fttml2-WD-201605XX%2Fspec%2Fttml2.html&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2015

So, I'm lost at this point since I can't even debug the rule. Maybe the libraries on the server aren't up-to-date or something?

**Comment by tripu** [comment] 2016-05-17 07:31
Duplicate of #351.
@plehegar, it's fixed, but not deployed in production yet.

**Closed by tripu** 2016-05-17 07:31 UTC
Labels: bug, duplicate

**Comment by plehegar** [comment] 2016-05-17 18:00
can we deployed into production since that would allow me to update the Timed Text Working Draft?

**Comment by plehegar** [comment] 2016-05-17 18:04
actually, discard that last comment. I can do the change on my end for the time being.

**Comment by tripu** [comment] 2016-05-18 07:19
@plehegar, thanks. We're holding the next deployment of Specberus a few days to be consistent with Echidna and do more tests.

**Comment by deniak** [comment] 2016-05-30 15:54
The fix has been deployed!
